views:
  - output: "hpa/index.md"
    template: "hpa-index.md"
  - output: "hpa/model.md"
    query: "hpa-model.rq"
    template: "hpa-model.md"
  - output: "hpa/genes.md"
    query: "hpa-genes.rq"
    template: "hpa-genes.md"
  - output: "hpa/antibodies.md"
    query: "hpa-antibodies.rq"
    template: "hpa-antibodies.md"
  - output: "hpa/antibodies/{{name}}.md"
    query: "hpa-antibody.rq"
    template: "hpa-antibody.md"
